<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <RootNamespace>OpenPayments.Sdk.HttpSignatureUtils.Tests</RootNamespace>
    <AssemblyName>OpenPayments.Sdk.HttpSignatureUtils.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector"/>
    <PackageReference Include="AwesomeAssertions"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="Moq"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio"/>
    <ProjectReference Include="..\OpenPayments.Sdk.HttpSignatureUtils\OpenPayments.Sdk.HttpSignatureUtils.csproj" />
  </ItemGroup>
</Project>
