<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Interledger.OpenPayments.HttpSignatureUtils</RootNamespace>
    <PackageId>Interledger.OpenPayments.HttpSignatureUtils</PackageId>
    <Authors>Interledger.OpenPayments.HttpSignatureUtils</Authors>
    <Company>Interledger</Company>
    <Product>OpenPayments.HttpSignatureUtils</Product>
    <AssemblyName>Interledger.OpenPayments.HttpSignatureUtils</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NSec.Cryptography"/>
    <PackageReference Include="Portable.BouncyCastle"/>
    <PackageReference Include="Sodium.Core"/>
    <PackageReference Include="Newtonsoft.Json"/>
    <InternalsVisibleTo Include="Interledger.OpenPayments.HttpSignatureUtils.Tests"/>
  </ItemGroup>
</Project>
