<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Interledger.OpenPayments</PackageId>
    <Description>.NET SDK for OpenPayments</Description>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>Interledger.OpenPayments</AssemblyName>
    <RootNamespace>Interledger.OpenPayments</RootNamespace>
    <PackageTags>interledger openpayments</PackageTags>
    <Product>Interledger.OpenPayments</Product>
    <LangVersion>12</LangVersion>
    <Title>OpenPayments SDK</Title>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="all"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
    <PackageReference Include="Microsoft.Extensions.Http"/>
    <PackageReference Include="Newtonsoft.Json"/>
    <PackageReference Include="NSec.Cryptography"/>
    <AdditionalFiles Include="PublicAPI.Shipped.txt"/>
    <AdditionalFiles Include="PublicAPI.Unshipped.txt"/>
    <ProjectReference Include="..\OpenPayments.Sdk.HttpSignatureUtils\OpenPayments.Sdk.HttpSignatureUtils.csproj" />
    <None Include="../README.md" Pack="true" PackagePath=""/>
    <None Include="icon.png" Pack="true" PackagePath=""/>
  </ItemGroup>
</Project>
